version: "3.9"
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db_co
    restart: unless-stopped
    ports:
      - 8008:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - ./data:/data/db
    env_file:
      - .env
# networks:
#   default:
#     external: true
#     name: nikolaydemidovez_network
